server:
  port: 38021
  servlet:
    context-path: /at-api

spring:
  application:
    name: wx_at_atp_api_web
  profiles:
    active: dev
  jackson:
    date-format:  "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+08:00"
    default-property-inclusion: non_empty
